routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('discussions', 'DiscussionsController')->middleware('auth');
Route::get('mydiscussions', 'DiscussionsController@myDiscussions')->name('discussions.mydiscussions')->middleware('auth');
Route::get('discussions/delete/{id}', 'DiscussionsController@destroy')->name('discussion.delete');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Discussion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Discussion extends Model
{
    protected $fillable = ['date', 'hall_id', 'judge_id', 'writer_id', 'type_id'];

    public function judge(){
        return $this->belongsTo('App\Judge');
    }
    public function writer(){
        return $this->belongsTo('App\Writer');
    }
    public function hall(){
        return $this->belongsTo('App\Hall');
    }
    public function type(){
        return $this->belongsTo('App\Type');
    }
    
    
}

app/Hall.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hall extends Model
{
    public function discussion(){
        return $this->hasMany('App\Discussion');
    }
}

app/Judge.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Judge extends Model
{
    public function discussion(){
        return $this->hasMany('App\Discussion');
    }
    public function type(){
        return $this->belongsTo('App\Type');
        //moshe   
        //yeled
        //niuyuiehfinefjiohjg
    }
}

app/Type.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Type extends Model
{
    public function discussion(){
        return $this->hasMany('App\Discussion');
    }
    public function judge(){
        return $this->hasMany('App\Judge');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Writer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Writer extends Model
{
    public function discussion(){
        return $this->hasMany('App\Discussion');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DiscussionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Discussion;
use App\Hall;
use App\Judge;
use App\Type;
use App\Writer;
use App\User;
class DiscussionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $discussions = Discussion::all();
        $halls = Hall::all();
        $judges = Judge::all();  
        $types = Type::all();
        $writers = Writer::all();
        $users = User::all();      
        return view('discussions.index', compact('discussions','halls', 'judges','types','writers','users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('discussions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $discussion = new Discussion();
        $dis = $discussion->create($request->all());
        $dis->save();
        return redirect('discussions');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/discussions/create.blade.php
@extends('layouts.app')

@section('title', 'Create discussion')

@section('content')
        <h1>Create discussion</h1>
        <form method = "post" action = "{{action('DiscussionsController@store')}}">
        @csrf 
        <div class="form-group">
            <label for = "name">Discussion name</label>
            <input type = "text" class="form-control" name = "name">
        </div>     
        <div class="form-group">
            <label for = "date">Discussion date</label>
            <input type = "date" class="form-control" name = "date">
        </div> 
        <div class="form-group">
            <label for = "hall">hall_id</label>
            <input type = "text" class="form-control" name = "hall_id">
            </div> 
            <div class="form-group">
            <label for = "judge">judge_id</label>
            <input type = "text" class="form-control" name = "judge_id">
            </div> 
            <div class="form-group">
            <label for = "writer">writer_id</label>
            <input type = "text" class="form-control" name = "writer">
            </div> 
            <div class="form-group">
            <label for = "type">type_id</label>
            <input type = "text" class="form-control" name = "type">
            </div> 
        <div>
            <input type = "submit" name = "submit" value = "Create discussion">
        </div>                       
        </form>    
@endsection

resources/views/discussions/index.blade.php
@extends('layouts.app')
@section('title', 'Discussions')
@section('content')

<div><a href =  "{{url('/discussions/create')}}"> Add new discussion</a></div>
<h1>List of discussions</h1>
<table class = "table table-dark">
    <tr>
        <th>id</th><th>Date</th><th>Hall name</th><th>Judge name</th><th>Writer name</th><th>discussion type</th>
    </tr>
    
    @foreach($discussions as $discussion)
        <tr>
            <td>{{$discussion->id}}</td>
            <td>{{$discussion->date}}</td>
            <td>{{$discussion->hall->name}}</td>
            <td>{{$discussion->judge->name}}</td>
            <td>{{$discussion->writer->name}}</td>
            <td>{{$discussion->type->name}}</td>
            

           
            <td>
                <a href = "{{route('discussions.edit',$discussion->id)}}">Edit</a>
            </td> 
            <td>
                    <a href = "{{route('discussion.delete',$discussion->id)}}">Delete</a>
            </td>                                                               
        </tr>
    @endforeach
</table>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title> @yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        
            <div class="container">
                <a class="navbar-brand" href="{{ url('/discussions') }}">
                    discussions
                </a>
                <a class="navbar-brand" href="{{ route('discussions.mydiscussions') }}">
                   My discussions
                 </a>                   
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>